# Generated by Django 4.1.2 on 2022-10-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='context',
            new_name='content',
        ),
    ]
